apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-git-ops
  namespace: seti-labs-rd
spec:
  distribution:
    fullVersion: v1.18.10+vmware.1-tkg.1.3a6cd48.629                          #The full image name is specified
  topology:
    controlPlane:
      count: 1                                 #3 control plane nodes
      class: best-effort-medium               #large size VM
      storageClass: k8s-policy #Specific storage class for control plane
    workers:
      count: 1                              #5 worker nodes
      class: best-effort-medium              #extra large size VM
      storageClass: k8s-policy   #Specific storage class for workers
  settings:
    storage:
      classes: ["k8s-policy"]           #Named PVC storage classes
      defaultClass: k8s-policy                  #Default PVC storage class
