#!/bin/bash

VSPHERE_WITH_TANZU_CONTROL_PLANE_IP=10.40.14.65
VSPHERE_WITH_TANZU_USERNAME=${VSPEHRE_USER}
VSPHERE_WITH_TANZU_PASSWORD=${VSPEHRE_PASS}

echo ${VSPHERE_WITH_TANZU_USERNAME}

KUBECTL_VSPHERE_PATH=/usr/bin/kubectl-vsphere
KUBECTL_PATH=/usr/bin/kubectl

KUBECTL_VSPHERE_LOGIN_COMMAND=$(expect -c "
spawn $KUBECTL_VSPHERE_PATH login --server=$VSPHERE_WITH_TANZU_CONTROL_PLANE_IP --vsphere-username $VSPHERE_WITH_TANZU_USERNAME --insecure-skip-tls-verify
expect \"*?assword:*\"
send -- \"$VSPHERE_WITH_TANZU_PASSWORD\r\"
expect eof
")

${KUBECTL_PATH} config use-context $VSPHERE_WITH_TANZU_CONTROL_PLANE_IP
